[package]
name = "advent_of_code_2015"
version = "0.1.0"
authors = ["Aidiakapi"]

[dependencies]
reqwest = "0.8.6"
rust-crypto = "0.2.36"
serde = "1.0.70"
serde_derive = "1.0.70"
ron = "0.3.0"
itertools = "0.7.8"